apiVersion: v1
kind: ConfigMap
metadata:
  name: stress-test-values
data:
  NAMESPACE: couchdb
  COUCHDB_SVC: couchdb-svc-couchdb
  COUCHDB_PORT: "5984"
  COUCHDB_DB_NAMES: "db1 db2"
  COUCHDB_INSERT_ROWS: "10000"
  COUCHDB_N_IT: "100"
  POD_NAMES: "couchdb-couchdb-0 couchdb-couchdb-1 couchdb-couchdb-2"
  VOLUME_THRESHOLD: "0.5"
  VOLUME_RESIZE_PERCENTAGE: "1.3"
  MOUNT_VOLUME_PATH: "opt/couchdb/data"
  VIEW_NAME: "order_by_date"
  VIEW_STRING: '{"views":{"order_by_date":{"map":"function(doc) { if(doc.date && doc.name) { emit(doc.date, doc.name); }}"}}}'