apiVersion: v1
kind: ConfigMap
metadata:
  name: stress-test-values
data:
  adminUsername: UIVpSuacnjZtpnkn
  adminPassword: rqpeXxgcwojKLTVu
  NAMESPACE: couchdb
  COUCHDB_SVC: couchdb-cluster.aws-playground.caligrafix.cl
  COUCHDB_PORT: "80"
  COUCHDB_DB_NAMES: "db1"
  COUCHDB_INSERT_ROWS: "10000"
  COUCHDB_N_IT: "100"
  POD_NAMES: "couchdb-couchdb-0 couchdb-couchdb-1 couchdb-couchdb-2"
  VOLUME_THRESHOLD: "0.5"
  VOLUME_RESIZE_PERCENTAGE: "1.3"
  MOUNT_VOLUME_PATH: "opt/couchdb/data"
  VIEW_NAME: "order_by_phone_age"
  VIEW_STRING: '{"views":{"order_by_phone_age":{"map":"function(doc) { if(doc.phone_number && doc.age) { emit(doc.phone_number, doc.age); }}"}}}'