apiVersion: v1
kind: Pod
metadata:
  name: couchdb-k8s-stress-tests-s-0
  labels:
    type: Stress-test
spec:
  containers:
  - name: couchdb-k8s-stress-tests
    image: caligrafix/couchdb-autoscaler-tests:latest
    args: ["--scenario", "0"]
    imagePullPolicy: Always
    envFrom:
      - secretRef:
          name: couchdb-couchdb
      - configMapRef:
          name: stress-test-values
  restartPolicy: Never