apiVersion: v1
kind: Pod
metadata:
  name: couchdb-k8s-stress-5
  labels:
    type: Stress-test
spec:
  containers:
  - name: stress-populate-database
    image: caligrafix/couchdb-autoscaler-tests:latest
    args: ["--scenario", "5"]
    imagePullPolicy: Always
    envFrom:
      - configMapRef:
          name: stress-test-values
  restartPolicy: Never
